development:
  adapter: postgresql
  encoding: unicode
  database: biblioteca_de_filmes_development
  host: localhost
  pool: 5
  username: postgres
  password: postgres
  port: 5432

  
test:
    adapter: postgresql
    encoding: unicode
    database: biblioteca_de_filmes_test
    host: localhost
    pool: 5
    port: 5432
    username: postgres
    password: postgres